name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Start stack
        run: |
          ls
          cat package.json
          docker-compose --help
          npm run resetStack
      - name: Start dev server
        working-directory: server
        run: |
          npm install
          node fixtures
          node app.js
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress tests on chrome
        uses: cypress-io/github-action@v2
        with:
          working-directory: client
          browser: chrome
          build: npm run build
          start: npm start
